### ISSUE TITLE
sla_class in app autotune yaml is not a mandatory field

### ISSUE THREAD

**Issue by shruacha1234** [kruize/autotune#111]
sla_class in app autotune yaml is not a mandatory field, currently DA is throwing error no-slaclass, null-slaclass, no-slaclass-value, blank-slaclass
Expected behaviour:  DA should create the object for the above cases

**Comment by shruacha1234** [comment]
Needs discussion

**Comment by chandrams** [comment]
Output for no-sloclass, null-sloclass, no-sloclass-value, blank-sloclass with autotune 0.0.5
```
>>cat blank-sloclass-autotune.log 
com.autotune.analyzer.exceptions.InvalidValueException: slo_class:   not supported
	at com.autotune.analyzer.k8sObjects.SloInfo.<init>(SloInfo.java:58)
	at com.autotune.analyzer.deployment.AutotuneDeployment.getAutotuneObject(AutotuneDeployment.java:311)
	at com.autotune.analyzer.deployment.AutotuneDeployment$1.eventReceived(AutotuneDeployment.java:94)
	at com.autotune.analyzer.deployment.AutotuneDeployment$1.eventReceived(AutotuneDeployment.java:87)
	at io.fabric8.kubernetes.client.dsl.internal.RawWatchConnectionManager$1.onMessage(RawWatchConnectionManager.java:133)
	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:323)
	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:219)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)



no-sloclass

cat no-sloclass-autotune.log 
com.autotune.analyzer.exceptions.InvalidValueException: slo_class:  not supported
	at com.autotune.analyzer.k8sObjects.SloInfo.<init>(SloInfo.java:58)
	at com.autotune.analyzer.deployment.AutotuneDeployment.getAutotuneObject(AutotuneDeployment.java:311)
	at com.autotune.analyzer.deployment.AutotuneDeployment$1.eventReceived(AutotuneDeployment.java:94)
	at com.autotune.analyzer.deployment.AutotuneDeployment$1.eventReceived(AutotuneDeployment.java:87)
	at io.fabric8.kubernetes.client.dsl.internal.RawWatchConnectionManager$1.onMessage(RawWatchConnectionManager.java:133)
	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:323)
	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:219)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

no-sloclass-value

>> cat no-sloclass-value.log 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                    Running Testcase slo_class
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*******----------- Running test for no-sloclass-value ----------*******
CMD=kubectl apply -f /home/csubrama/github/chandra/autotune-id/autotune/tests/autotune_test_yamls/manifests/da/app_autotune_yaml/slo_class/no-sloclass-value.yaml
The Autotune "no-sloclass-value" is invalid: spec.slo.slo_class: Invalid value: "null": spec.slo.slo_class in body must be of type string: "null"
autotune object no-sloclass-value did not get created
Expected message is : com.autotune.analyzer.deployment.AutotuneDeployment - Added autotune object no-sloclass-value
Test failed
--------------------------------------------------------------------------------

>> cat no-sloclass-value-autotune.log - blank

null-sloclass

>> cat null-sloclass.log 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                    Running Testcase slo_class
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*******----------- Running test for null-sloclass ----------*******
CMD=kubectl apply -f /home/csubrama/github/chandra/autotune-id/autotune/tests/autotune_test_yamls/manifests/da/app_autotune_yaml/slo_class/null-sloclass.yaml
The Autotune "null-sloclass" is invalid: spec.slo.slo_class: Invalid value: "null": spec.slo.slo_class in body must be of type string: "null"
autotune object null-sloclass did not get created
Expected message is : com.autotune.analyzer.deployment.AutotuneDeployment - Added autotune object null-sloclass
Test failed
--------------------------------------------------------------------------------

>> cat null-sloclass-autotune.log - blank
```
