### ISSUE TITLE
 403 unexpected response status encountered checking Prometheus reachability 

### ISSUE THREAD

**Issue by shreyabiradar07** [kruize/autotune#1267]
**Describe the bug**
A 403 unexpected status error is encountered when trying to check for Prometheus datasource reachability and adding it to the database. The error occurs intermittently, indicating that the server is refusing the request.

**How to reproduce it**
Running  the `local_monitoring_demo.sh` script either using a ResourceHub or Scalelab openshift cluster 
Please Note: this issue currently is seen 1/5 times by running the demo script / re-deploying Kruize

**Expected behavior**
The client should be able to successfully connect and retrieve data from the Prometheus server without encountering a 403 Forbidden error.

**Relevant logs**
```
2024-08-2112:27:26.352 INFO [main][DataSourceCollection.java(47)]-Checking available datasources from database:
2024-08-2112:27:26.541 INFO [main][DataSourceCollection.java(50)]-No datasource found in database.
2024-08-2112:27:26.608 INFO [main][DataSourceCollection.java(89)]-Trying to add the datasource to collection: prometheus-1
2024-08-2112:27:26.608 INFO [main][DataSourceCollection.java(97)]-Verifying datasource reachability status: prometheus-1
org.apache.http.client.ClientProtocolException: Unexpected response status: 403
	at com.autotune.utils.GenericRestApiClient$StringResponseHandler.handleResponse(GenericRestApiClient.java:176)
	at com.autotune.utils.GenericRestApiClient$StringResponseHandler.handleResponse(GenericRestApiClient.java:168)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:223)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:165)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:140)
	at com.autotune.utils.GenericRestApiClient.fetchMetricsJson(GenericRestApiClient.java:162)
	at com.autotune.common.datasource.prometheus.PrometheusDataOperatorImpl.getJsonObjectForQuery(PrometheusDataOperatorImpl.java:148)
	at com.autotune.common.datasource.prometheus.PrometheusDataOperatorImpl.getValueForQuery(PrometheusDataOperatorImpl.java:106)
	at com.autotune.common.datasource.prometheus.PrometheusDataOperatorImpl.isServiceable(PrometheusDataOperatorImpl.java:81)
	at com.autotune.common.datasource.DataSourceCollection.addDataSource(DataSourceCollection.java:99)
	at com.autotune.common.datasource.DataSourceCollection.addDataSourcesFromConfigFile(DataSourceCollection.java:165)
	at com.autotune.Autotune.setUpDataSources(Autotune.java:175)
	at com.autotune.Autotune.main(Autotune.java:115)
2024-08-2112:27:27.954 ERROR [main][DataSourceCollection.java(119)]-Datasource is not serviceable.
```

**Environment:**
- Kubernetes Cluster: Openshift
- Version: 
Client Version: v1.29.7
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.23.12

- OS: Fedora

**Additional context**
.

**Comment by shreyabiradar07** [comment]
Closing the issue as PR [1278](https://github.com/kruize/autotune/pull/1278) fixes 403 Prometheus reachability error and is merged.
