### ISSUE TITLE
Datasource is either missing or is invalid error with Bulk demo with thanos datasource

### ISSUE THREAD

**Issue by chandrams** [kruize/autotune#1356]
**Describe the bug**

Got a Datasource is either missing or is invalid error with Bulk demo with thanos datasource

```
Waiting for experiments ... 
2024-10-2904:05:49.010 INFO [qtp351877391-50][MetricProfileCollection.java(66)]-Trying to add the metric profile to collection: resource-optimization-local-monitoring
2024-10-2904:05:49.011 INFO [qtp351877391-50][MetricProfileCollection.java(71)]-MetricProfile added to the collection successfully: resource-optimization-local-monitoring
2024-10-2904:05:49.541 ERROR [pool-5-thread-1][BulkJobManager.java(203)]-Datasource is either missing or is invalid
java.lang.Exception: Datasource is either missing or is invalid
	at com.autotune.common.utils.CommonUtils.getDataSourceInfo(CommonUtils.java:310)
	at com.autotune.analyzer.workerimpl.BulkJobManager.run(BulkJobManager.java:109)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```
**How to reproduce it**
Run the bulk demo from kruize-demos with thanos as datasource 

**Expected behavior**
Datasource should be detected and no error seen

**Relevant logs**
Attach any relevant logs to help debug the issue

**Environment:**
- Kubernetes Cluster openshift

**Comment by chandrams** [comment]
This issue has been fixed now.
