### ISSUE TITLE
 Import metadata failed with unexpected response 400

### ISSUE THREAD

**Issue by chandrams** [kruize/autotune#1377]
**Describe the bug**
Importing metadata failed with the below error:

```
Importing the metadata...
URL =  http://kruize-openshift-tuning.apps.kruize-scalelab.h0b5.p1.openshiftapps.com/dsmetadata
Response status code =  500
{
    "message": "Internal Server Error: Unexpected response status: 400",
    "httpcode": 500,
    "documentationLink": "",
    "status": "ERROR"
}
{'message': 'Internal Server Error: Unexpected response status: 400', 'httpcode': 500, 'documentationLink': '', 'status': 'ERROR'}
Importing metadata from the datasource failed!
```

**How to reproduce it**

- Deploy kruize with thanos as datasource
- Create the metric profile
- Import datasource metadata

**Expected behavior**
Import metadata should fetch the metadata related to the registered datasource

**Relevant logs**
From the kruize pod log
```
2024-11-1907:36:00.490 INFO [qtp1446922577-49][DataSourceMetadataOperator.java(193)]-containerQuery: sum by (container, image, workload, workload_type, namespace) (  avg_over_time(kube_pod_container_info{container!="" }[15d]) *  on (pod, namespace,prometheus_replica) group_left(workload, workload_type)   avg_over_time(namespace_workload_pod:kube_pod_owner:relabel{workload!="" }[15d]))
org.apache.http.client.ClientProtocolException: Unexpected response status: 400
	at com.autotune.utils.GenericRestApiClient$StringResponseHandler.handleResponse(GenericRestApiClient.java:213)
	at com.autotune.utils.GenericRestApiClient.fetchMetricsJson(GenericRestApiClient.java:111)
	at com.autotune.common.datasource.DataSourceMetadataOperator.fetchQueryResults(DataSourceMetadataOperator.java:262)
	at com.autotune.common.datasource.DataSourceMetadataOperator.processQueriesAndPopulateDataSourceMetadataInfo(DataSourceMetadataOperator.java:195)
```

**Environment:**
- Kubernetes Cluster : openshift

**Comment by chandrams** [comment]
I see this error with prometheus datasource

```
Waiting for experiments ... 
2024-11-2018:57:53.685 INFO [qtp1446922577-47][MetricProfileCollection.java(66)]-Trying to add the metric profile to collection: resource-optimization-local-monitoring
2024-11-2018:57:53.685 INFO [qtp1446922577-47][MetricProfileCollection.java(71)]-MetricProfile added to the collection successfully: resource-optimization-local-monitoring
2024-11-2018:57:54.260 INFO [pool-5-thread-1][DataSourceMetadataOperator.java(191)]-namespaceQuery: sum by (namespace) ( avg_over_time(kube_namespace_status_phase{namespace!="" }[15d]))
2024-11-2018:57:54.260 INFO [pool-5-thread-1][DataSourceMetadataOperator.java(192)]-workloadQuery: sum by (namespace, workload, workload_type) ( avg_over_time(namespace_workload_pod:kube_pod_owner:relabel{workload!="" }[15d]))
2024-11-2018:57:54.260 INFO [pool-5-thread-1][DataSourceMetadataOperator.java(193)]-containerQuery: sum by (container, image, workload, workload_type, namespace) (  avg_over_time(kube_pod_container_info{container!="" }[15d]) *  on (pod, namespace,prometheus_replica) group_left(workload, workload_type)   avg_over_time(namespace_workload_pod:kube_pod_owner:relabel{workload!="" }[15d]))
2024-11-2018:57:54.295 ERROR [pool-5-thread-1][DataSourceManager.java(73)]-DataSourceMetadataInfo is null. Metadata is not populated.

```

**Comment by chandrams** [comment]
Verified this issue with the latest build in mvp_demo, issue is not seen, closing this.
