### ISSUE TITLE
autotune container error.

### ISSUE THREAD

**Issue by moelhoussein** [kruize/autotune#532]
Hello team,

I deployed autotune on minikube. The autotune pod is running,  but when I port forward and access the UI, all I see is "-1"
After reviewing the logs I found this in the autotune container logs.

`kubectl logs autotune-7c4559c8cd-2r5mh -n monitoring -c autotune
2022-11-24 17:50:46.377:INFO::main: Logging initialized @1171ms to org.eclipse.jetty.util.log.StdErrLog
17:50:48.011 [main] INFO  com.autotune.analyzer.deployment.DeploymentInfo - Cluster Type: kubernetes
17:50:48.015 [main] INFO  com.autotune.analyzer.deployment.DeploymentInfo - Kubernetes Type: minikube
17:50:48.015 [main] INFO  com.autotune.analyzer.deployment.DeploymentInfo - Auth Type:
17:50:48.016 [main] INFO  com.autotune.analyzer.deployment.DeploymentInfo - Monitoring Agent: prometheus
17:50:48.016 [main] INFO  com.autotune.analyzer.deployment.DeploymentInfo - Monitoring Agent URL: http://10.102.76.48:9090
17:50:48.016 [main] INFO  com.autotune.analyzer.deployment.DeploymentInfo - Monitoring agent service: prometheus-k8s

17:50:48.107 [OkHttp https://10.96.0.1/...] INFO  io.fabric8.kubernetes.client.dsl.internal.RawWatchConnectionManager - Websocket opened
17:50:48.127 [OkHttp https://10.96.0.1/...] INFO  io.fabric8.kubernetes.client.dsl.internal.RawWatchConnectionManager - Websocket opened
17:50:48.130 [main] INFO  com.autotune.experimentManager.core.EMExecutorService - Creating regular executor
17:50:48.131 [main] INFO  com.autotune.experimentManager.core.EMExecutorService - Creating scheduled executor
17:50:48.131 [main] INFO  com.autotune.experimentManager.core.EMExecutorService - Starting stage processors
17:50:48.132 [main] INFO  com.autotune.experimentManager.core.EMExecutorService - Starting stage processors
com.autotune.analyzer.exceptions.InvalidValueException: Layer presence missing! Must be indicated through a presence field, layerPresenceQuery or layerPresenceLabel

        at com.autotune.analyzer.k8sObjects.AutotuneConfig.<init>(AutotuneConfig.java:89)
        at com.autotune.analyzer.deployment.AutotuneDeployment.getAutotuneConfig(AutotuneDeployment.java:495)
        at com.autotune.analyzer.deployment.AutotuneDeployment$2.eventReceived(AutotuneDeployment.java:127)
        at com.autotune.analyzer.deployment.AutotuneDeployment$2.eventReceived(AutotuneDeployment.java:120)
        at io.fabric8.kubernetes.client.dsl.internal.RawWatchConnectionManager$1.onMessage(RawWatchConnectionManager.java:133)
        at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:323)
        at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:219)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274)
        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
com.autotune.analyzer.exceptions.InvalidValueException: Layer presence missing! Must be indicated through a presence field, layerPresenceQuery or layerPresenceLabel

        at com.autotune.analyzer.k8sObjects.AutotuneConfig.<init>(AutotuneConfig.java:89)
        at com.autotune.analyzer.deployment.AutotuneDeployment.getAutotuneConfig(AutotuneDeployment.java:495)
        at com.autotune.analyzer.deployment.AutotuneDeployment$2.eventReceived(AutotuneDeployment.java:127)
        at com.autotune.analyzer.deployment.AutotuneDeployment$2.eventReceived(AutotuneDeployment.java:120)
        at io.fabric8.kubernetes.client.dsl.internal.RawWatchConnectionManager$1.onMessage(RawWatchConnectionManager.java:133)
        at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:323)
        at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:219)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274)
        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
com.autotune.analyzer.exceptions.InvalidValueException: Layer presence missing! Must be indicated through a presence field, layerPresenceQuery or layerPresenceLabel

        at com.autotune.analyzer.k8sObjects.AutotuneConfig.<init>(AutotuneConfig.java:89)
        at com.autotune.analyzer.deployment.AutotuneDeployment.getAutotuneConfig(AutotuneDeployment.java:495)
        at com.autotune.analyzer.deployment.AutotuneDeployment$2.eventReceived(AutotuneDeployment.java:127)
        at com.autotune.analyzer.deployment.AutotuneDeployment$2.eventReceived(AutotuneDeployment.java:120)
        at io.fabric8.kubernetes.client.dsl.internal.RawWatchConnectionManager$1.onMessage(RawWatchConnectionManager.java:133)
        at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:323)
        at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:219)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274)
        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
18:33:03.596 [OkHttp https://10.96.0.1/...] INFO  io.fabric8.kubernetes.client.dsl.internal.RawWatchConnectionManager - Socket closing:
18:33:03.597 [OkHttp WebSocket https://10.96.0.1/...] DEBUG io.fabric8.kubernetes.client.dsl.internal.RawWatchConnectionManager - WebSocket close received. code: 1000, reason:
18:33:03.597 [OkHttp WebSocket https://10.96.0.1/...] DEBUG io.fabric8.kubernetes.client.dsl.internal.RawWatchConnectionManager - Submitting reconnect task to the executor
18:33:03.599 [scheduleReconnect|Executor for Watch 1261052442] DEBUG io.fabric8.kubernetes.client.dsl.internal.RawWatchConnectionManager - Scheduling reconnect task
18:33:03.599 [scheduleReconnect|Executor for Watch 1261052442] DEBUG io.fabric8.kubernetes.client.dsl.internal.RawWatchConnectionManager - Current reconnect backoff is 1000 milliseconds (T0)
18:33:04.613 [OkHttp https://10.96.0.1/...] INFO  io.fabric8.kubernetes.client.dsl.internal.RawWatchConnectionManager - Websocket opened
com.autotune.analyzer.exceptions.InvalidValueException: Layer presence missing! Must be indicated through a presence field, layerPresenceQuery or layerPresenceLabel

        at com.autotune.analyzer.k8sObjects.AutotuneConfig.<init>(AutotuneConfig.java:89)
        at com.autotune.analyzer.deployment.AutotuneDeployment.getAutotuneConfig(AutotuneDeployment.java:495)
        at com.autotune.analyzer.deployment.AutotuneDeployment$2.eventReceived(AutotuneDeployment.java:127)
        at com.autotune.analyzer.deployment.AutotuneDeployment$2.eventReceived(AutotuneDeployment.java:120)
        at io.fabric8.kubernetes.client.dsl.internal.RawWatchConnectionManager$1.onMessage(RawWatchConnectionManager.java:133)
        at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:323)
        at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:219)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274)
        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
com.autotune.analyzer.exceptions.InvalidValueException: Layer presence missing! Must be indicated through a presence field, layerPresenceQuery or layerPresenceLabel

        at com.autotune.analyzer.k8sObjects.AutotuneConfig.<init>(AutotuneConfig.java:89)
        at com.autotune.analyzer.deployment.AutotuneDeployment.getAutotuneConfig(AutotuneDeployment.java:495)
        at com.autotune.analyzer.deployment.AutotuneDeployment$2.eventReceived(AutotuneDeployment.java:127)
        at com.autotune.analyzer.deployment.AutotuneDeployment$2.eventReceived(AutotuneDeployment.java:120)
        at io.fabric8.kubernetes.client.dsl.internal.RawWatchConnectionManager$1.onMessage(RawWatchConnectionManager.java:133)
        at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:323)
        at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:219)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274)
        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
com.autotune.analyzer.exceptions.InvalidValueException: Layer presence missing! Must be indicated through a presence field, layerPresenceQuery or layerPresenceLabel

        at com.autotune.analyzer.k8sObjects.AutotuneConfig.<init>(AutotuneConfig.java:89)
        at com.autotune.analyzer.deployment.AutotuneDeployment.getAutotuneConfig(AutotuneDeployment.java:495)
        at com.autotune.analyzer.deployment.AutotuneDeployment$2.eventReceived(AutotuneDeployment.java:127)
        at com.autotune.analyzer.deployment.AutotuneDeployment$2.eventReceived(AutotuneDeployment.java:120)
        at io.fabric8.kubernetes.client.dsl.internal.RawWatchConnectionManager$1.onMessage(RawWatchConnectionManager.java:133)
        at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:323)
        at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:219)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274)
        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)`

I ran into multiple issues running the autotune image build locally so I just pulled the kruize/autotune, and the kruize/operator images.

Please let me know how can I resolve this issue.

**Comment by dinogun** [comment]
@moelhoussein Thank you for trying Autotune. May I suggest that you try with the kruize-demos repo first. Try running the autotune [demo](https://github.com/kruize/kruize-demos/blob/main/autotune_minikube_demo_setup.sh) script and see if that comes up right for you. That should also have all the right links to tell you what is going on in the demo.
