### ISSUE TITLE
Stress test failed with NPE: Cannot invoke "com.autotune.analyzer.kruizeObject.KruizeObject.getClusterName()

### ISSUE THREAD

**Issue by chandrams** [kruize/autotune#958]
Stress test failed with the below error:

```
2023-09-1823:08:18.081 INFO [main][EMExecutorService.java(67)]-Starting stage processors
2023-09-1823:08:18.081 INFO [main][EMExecutorService.java(67)]-Starting stage processors
Waiting for experiments ... 
2023-09-1823:14:02.624 ERROR [qtp88397182-43][SqlExceptionHelper.java(138)]-ERROR: no partition of relation "kruize_results" found for row
  Detail: Partition key of the failing row contains (interval_end_time) = (2023-09-19 04:59:02.072).
2023-09-1823:14:02.629 ERROR [qtp88397182-43][ExperimentDAOImpl.java(171)]-ERROR: no partition of relation "kruize_results" found for row
  Detail: Partition key of the failing row contains (interval_end_time) = (2023-09-19 04:59:02.072).
2023-09-1823:14:02.630 INFO [qtp88397182-43][ExperimentDAOImpl.java(177)]-Create partition and retry !
2023-09-1823:14:59.109 ERROR [qtp88397182-43][SqlExceptionHelper.java(138)]-ERROR: no partition of relation "kruize_results" found for row
  Detail: Partition key of the failing row contains (interval_end_time) = (2023-09-19 23:59:59.043).
2023-09-1823:14:59.109 ERROR [qtp88397182-43][ExperimentDAOImpl.java(171)]-ERROR: no partition of relation "kruize_results" found for row
  Detail: Partition key of the failing row contains (interval_end_time) = (2023-09-19 23:59:59.043).
2023-09-1823:14:59.109 INFO [qtp88397182-43][ExperimentDAOImpl.java(177)]-Create partition and retry !
2023-09-1823:14:59.119 ERROR [qtp88397182-43][SqlExceptionHelper.java(138)]-ERROR: no partition of relation "kruize_results" found for row
  Detail: Partition key of the failing row contains (interval_end_time) = (2023-09-19 23:59:59.043).
2023-09-1823:14:59.120 ERROR [qtp88397182-43][ExperimentDAOImpl.java(195)]-Converting `org.hibernate.exception.ConstraintViolationException` to JPA `PersistenceException` : could not execute statement
2023-09-1823:18:00.718 ERROR [qtp88397182-40][DBHelpers.java(328)]-Error while converting ExperimentResultData to ExperimentResultsTable due to Cannot invoke "com.autotune.analyzer.kruizeObject.KruizeObject.getClusterName()" because the return value of "java.util.concurrent.ConcurrentHashMap.get(Object)" is null
java.lang.NullPointerException: Cannot invoke "com.autotune.analyzer.kruizeObject.KruizeObject.getClusterName()" because the return value of "java.util.concurrent.ConcurrentHashMap.get(Object)" is null
	at com.autotune.database.helper.DBHelpers$Converters$KruizeObjectConverters.convertExperimentResultToExperimentResultsTable(DBHelpers.java:307)
	at com.autotune.database.service.ExperimentDBService.addResultsToDB(ExperimentDBService.java:208)
	at com.autotune.analyzer.experiment.ExperimentInitiator.validateAndAddExperimentResults(ExperimentInitiator.java:170)
	at com.autotune.analyzer.services.UpdateResults.doPost(UpdateResults.java:85)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1631)
	at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:319)
	at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:273)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Unknown Source)
```

To recreate:

- git clone <kruize autotune repo>
- cd tests/scripts/remote_monitoring_tests/stress_test
- ./remote_monitoring_stress_test.sh -c minikube  -i quay.io/kruize/autotune_operator:0.0.19_mvp -u 100 -e 30 -d 120 -t 1200 -r /tmp/stress_test_results

**Comment by msvinaykumar** [comment]
Seems it requires clean restart with old tables deleted

**Comment by chandrams** [comment]
Tried again by deleting and restarting, it failed again with the below error:

```
2023-09-1904:12:32.985 ERROR [qtp88397182-44][SqlExceptionHelper.java(138)]-ERROR: no partition of relation "kruize_results" found for row
  Detail: Partition key of the failing row contains (interval_end_time) = (2023-09-19 09:55:33.666).
2023-09-1904:12:32.988 ERROR [qtp88397182-44][ExperimentDAOImpl.java(171)]-ERROR: no partition of relation "kruize_results" found for row
  Detail: Partition key of the failing row contains (interval_end_time) = (2023-09-19 09:55:33.666).
2023-09-1904:12:32.988 INFO [qtp88397182-44][ExperimentDAOImpl.java(177)]-Create partition and retry !
2023-09-1904:17:06.852 ERROR [qtp88397182-47][UpdateResults.java(111)]-Exception: HV000028: Unexpected exception during isValid call.
jakarta.validation.ValidationException: HV000028: Unexpected exception during isValid call.
	at org.hibernate.validator.internal.engine.constraintvalidation.ConstraintTree.validateSingleConstraint(ConstraintTree.java:186)
	at org.hibernate.validator.internal.engine.constraintvalidation.SimpleConstraintTree.validateConstraints(SimpleConstraintTree.java:66)
	at org.hibernate.validator.internal.engine.constraintvalidation.ConstraintTree.validateConstraints(ConstraintTree.java:75)
	at org.hibernate.validator.internal.metadata.core.MetaConstraint.doValidateConstraint(MetaConstraint.java:130)
	at org.hibernate.validator.internal.metadata.core.MetaConstraint.validateConstraint(MetaConstraint.java:123)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateMetaConstraint(ValidatorImpl.java:555)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateMetaConstraints(ValidatorImpl.java:537)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraintsForNonDefaultGroup(ValidatorImpl.java:529)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraintsForCurrentGroup(ValidatorImpl.java:447)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateInContext(ValidatorImpl.java:425)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validate(ValidatorImpl.java:172)
	at com.autotune.analyzer.experiment.ExperimentInitiator.validateAndAddExperimentResults(ExperimentInitiator.java:145)
	at com.autotune.analyzer.services.UpdateResults.doPost(UpdateResults.java:85)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1631)
	at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:319)
	at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:273)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException: Cannot invoke "com.autotune.analyzer.kruizeObject.KruizeObject.getTrial_settings()" because "kruizeObject" is null
	at com.autotune.analyzer.serviceObjects.verification.validators.TimeDifferenceValidator.isValid(TimeDifferenceValidator.java:46)
	at com.autotune.analyzer.serviceObjects.verification.validators.TimeDifferenceValidator.isValid(TimeDifferenceValidator.java:31)
	at org.hibernate.validator.internal.engine.constraintvalidation.ConstraintTree.validateSingleConstraint(ConstraintTree.java:180)
	... 45 more
```

**Comment by chandrams** [comment]
@msvinaykumar - I have restarted the stress test, now I see this error:

```
2023-09-2005:37:09.799 ERROR [qtp88397182-43][DBHelpers.java(328)]-Error while converting ExperimentResultData to ExperimentResultsTable due to Cannot invoke "com.autotune.analyzer.kruizeObject.KruizeObject.getClusterName()" because the return value of "java.util.concurrent.ConcurrentHashMap.get(Object)" is null
java.lang.NullPointerException: Cannot invoke "com.autotune.analyzer.kruizeObject.KruizeObject.getClusterName()" because the return value of "java.util.concurrent.ConcurrentHashMap.get(Object)" is null
        at com.autotune.database.helper.DBHelpers$Converters$KruizeObjectConverters.convertExperimentResultToExperimentResultsTable(DBHelpers.java:307)
        at com.autotune.database.service.ExperimentDBService.addResultsToDB(ExperimentDBService.java:208)
        at com.autotune.analyzer.experiment.ExperimentInitiator.validateAndAddExperimentResults(ExperimentInitiator.java:170)
        at com.autotune.analyzer.services.UpdateResults.doPost(UpdateResults.java:85)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
        at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1631)
        at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:319)
        at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:273)
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:516)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
        at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by chandrams** [comment]
Fault tolerant test has these errors in the pod log 

```
Waiting for experiments ... 
2023-09-2203:25:09.344 ERROR [qtp88397182-40][SqlExceptionHelper.java(138)]-ERROR: no partition of relation "kruize_results" found for row
  Detail: Partition key of the failing row contains (interval_end_time) = (2023-09-22 09:10:09.046).
2023-09-2203:25:09.347 ERROR [qtp88397182-40][ExperimentDAOImpl.java(179)]-ERROR: no partition of relation "kruize_results" found for row
  Detail: Partition key of the failing row contains (interval_end_time) = (2023-09-22 09:10:09.046).
2023-09-2203:25:09.347 INFO [qtp88397182-40][ExperimentDAOImpl.java(185)]-Create partition and retry !
2023-09-2203:25:11.661 ERROR [qtp88397182-40][CreateExperiment.java(124)]-Failed to create experiment: Experiment name already exists: quarkus-exp_0
2023-09-2203:25:11.720 ERROR [qtp88397182-47][CreateExperiment.java(124)]-Failed to create experiment: Experiment name already exists: quarkus-exp_0
2023-09-2203:25:16.040 ERROR [qtp88397182-47][CreateExperiment.java(124)]-Failed to create experiment: Experiment name already exists: quarkus-exp_0
java.lang.NullPointerException: Cannot invoke "java.util.HashMap.values()" because the return value of "com.autotune.common.data.result.ContainerData.getMetrics()" is null
	at com.autotune.analyzer.serviceObjects.Converters$KruizeObjectConverters.convertKruizeObjectToListRecommendationSO(Converters.java:240)
	at com.autotune.analyzer.services.ListExperiments.buildRecommendationsResponse(ListExperiments.java:383)
	at com.autotune.analyzer.services.ListExperiments.buildResponseBasedOnQuery(ListExperiments.java:288)
	at com.autotune.analyzer.services.ListExperiments.doGet(ListExperiments.java:153)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1631)
	at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:319)
	at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:273)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Unknown Source)
2023-09-2203:25:16.106 ERROR [qtp88397182-46][ListExperiments.java(391)]-Not able to generate recommendation for expName : quarkus-exp_0 due to Cannot invoke "java.util.List.iterator()" because "kubernetesAPIObjects" is null
2023-09-2203:25:16.135 ERROR [qtp88397182-46][ExperimentDBService.java(101)]-Unexpected error: Cannot invoke "com.autotune.analyzer.kruizeObject.KruizeObject.getClusterName()" because the return value of "com.autotune.analyzer.serviceObjects.UpdateResultsAPIObject.getKruizeObject()" is null
2023-09-2203:25:16.135 ERROR [qtp88397182-46][ExperimentDBService.java(101)]-Unexpected error: Cannot invoke "com.autotune.analyzer.kruizeObject.KruizeObject.getClusterName()" because the return value of "com.autotune.analyzer.serviceObjects.UpdateResultsAPIObject.getKruizeObject()" is null
2023-09-2203:25:16.135 ERROR [qtp88397182-46][ExperimentDBService.java(101)]-Unexpected error: Cannot invoke "com.autotune.analyzer.kruizeObject.KruizeObject.getClusterName()" because the return value of "com.autotune.analyzer.serviceObjects.UpdateResultsAPIObject.getKruizeObject()" is null
2023-09-2203:25:16.135 ERROR [qtp88397182-46][ExperimentDBService.java(101)]-Unexpected error: Cannot invoke "com.autotune.analyzer.kruizeObject.KruizeObject.getClusterName()" because the return value of "com.autotune.analyzer.serviceObjects.UpdateResultsAPIObject.getKruizeObject()" is null
```

**Comment by chandrams** [comment]
One of the issues mentioned above is seen with 0.0.18_rm #908 
```
java.lang.NullPointerException: Cannot invoke "java.util.HashMap.values()" because the return value of "com.autotune.common.data.result.ContainerData.getMetrics()" is null
	at com.autotune.analyzer.serviceObjects.Converters$KruizeObjectConverters.convertKruizeObjectToListRecommendationSO(Converters.java:240)
```

**Comment by chandrams** [comment]
This issue is not seen with Kruize rel 0.0.22, closing it.
