### ISSUE TITLE
Scalability test failed with Error while converting ExperimentResultData to ExperimentResultsTable due to null

### ISSUE THREAD

**Issue by chandrams** [kruize/autotune#959]
Scalability test failed on the new scalelab cluster (5k exps 15days) and AWS cluster (1k exps, 5 days) with the below error:

From the kruize pod log:

```
2023-09-1904:40:49.139 ERROR [qtp88397182-43][DurationBasedRecommendationEngine.java(693)]-Invalid Amount in CPU Section
2023-09-1904:40:49.139 ERROR [qtp88397182-43][DurationBasedRecommendationEngine.java(728)]-Invalid Amount in CPU Section
2023-09-1904:40:49.162 ERROR [qtp88397182-41][DurationBasedRecommendationEngine.java(693)]-Invalid Amount in CPU Section
2023-09-1904:40:49.162 ERROR [qtp88397182-41][DurationBasedRecommendationEngine.java(728)]-Invalid Amount in CPU Section
2023-09-1904:40:49.208 ERROR [qtp88397182-48][DBHelpers.java(328)]-Error while converting ExperimentResultData to ExperimentResultsTable due to null
2023-09-1904:40:49.208 ERROR [qtp88397182-48][DBHelpers.java(328)]-Error while converting ExperimentResultData to ExperimentResultsTable due to null
2023-09-1904:40:49.208 ERROR [qtp88397182-48][DBHelpers.java(328)]-Error while converting ExperimentResultData to ExperimentResultsTable due to null
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
2023-09-1904:40:49.208 ERROR [qtp88397182-48][DBHelpers.java(328)]-Error while converting ExperimentResultData to ExperimentResultsTable due to null
2023-09-1904:40:49.208 ERROR [qtp88397182-48][DBHelpers.java(328)]-Error while converting ExperimentResultData to ExperimentResultsTable due to null
java.lang.NullPointerException
2023-09-1904:40:49.208 ERROR [qtp88397182-48][DBHelpers.java(328)]-Error while converting ExperimentResultData to ExperimentResultsTable due to null
java.lang.NullPointerException
2023-09-1904:40:49.208 ERROR [qtp88397182-48][DBHelpers.java(328)]-Error while converting ExperimentResultData to ExperimentResultsTable due to null
java.lang.NullPointerException
2023-09-1904:40:49.208 ERROR [qtp88397182-48][DBHelpers.java(328)]-Error while converting ExperimentResultData to ExperimentResultsTable due to null
java.lang.NullPointerException
2023-09-1904:40:49.208 ERROR [qtp88397182-48][DBHelpers.java(328)]-Error while converting ExperimentResultData to ExperimentResultsTable due to null
java.lang.NullPointerException
2023-09-1904:40:49.208 ERROR [qtp88397182-48][DBHelpers.java(328)]-Error while converting ExperimentResultData to ExperimentResultsTable due to null
java.lang.NullPointerException
2023-09-1904:40:49.208 ERROR [qtp88397182-48][DBHelpers.java(328)]-Error while converting ExperimentResultData to ExperimentResultsTable due to null
java.lang.NullPointerException
2023-09-1904:40:49.208 ERROR [qtp88397182-48][DBHelpers.java(328)]-Error while converting ExperimentResultData to ExperimentResultsTable due to null
java.lang.NullPointerException
2023-09-1904:40:49.208 ERROR [qtp88397182-48][DBHelpers.java(328)]-Error while converting ExperimentResultData to ExperimentResultsTable due to null
java.lang.NullPointerException
2023-09-1904:40:49.208 ERROR [qtp88397182-48][DBHelpers.java(328)]-Error while converting ExperimentResultData to ExperimentResultsTable due to null
java.lang.NullPointerException
2023-09-1904:40:49.208 ERROR [qtp88397182-48][DBHelpers.java(328)]-Error while converting ExperimentResultData to ExperimentResultsTable due to null
java.lang.NullPointerException
2023-09-1904:40:49.208 ERROR [qtp88397182-48][DBHelpers.java(328)]-Error while converting ExperimentResultData to ExperimentResultsTable due to null
java.lang.NullPointerException
2023-09-1904:40:49.208 ERROR [qtp88397182-48][DBHelpers.java(328)]-Error while converting ExperimentResultData to ExperimentResultsTable due to null
java.lang.NullPointerException
2023-09-1904:40:49.213 ERROR [qtp88397182-48][ExperimentDAOImpl.java(217)]-Not able to save experiment due to Cannot invoke "com.autotune.database.table.KruizeResultsEntry.setErrorReasons(java.util.List)" because "entry" is null
2023-09-1904:40:49.213 ERROR [qtp88397182-48][UpdateResults.java(111)]-Exception: Cannot invoke "com.autotune.database.table.KruizeResultsEntry.setErrorReasons(java.util.List)" because "entry" is null
java.lang.NullPointerException: Cannot invoke "com.autotune.database.table.KruizeResultsEntry.setErrorReasons(java.util.List)" because "entry" is null
	at com.autotune.database.dao.ExperimentDAOImpl.lambda$addToDBAndFetchFailedResults$2(ExperimentDAOImpl.java:220)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at com.autotune.database.dao.ExperimentDAOImpl.addToDBAndFetchFailedResults(ExperimentDAOImpl.java:219)
	at com.autotune.database.service.ExperimentDBService.addResultsToDB(ExperimentDBService.java:211)
	at com.autotune.analyzer.experiment.ExperimentInitiator.validateAndAddExperimentResults(ExperimentInitiator.java:170)
	at com.autotune.analyzer.services.UpdateResults.doPost(UpdateResults.java:85)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1631)
	at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:319)
	at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:273)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Unknown Source)

```

**Comment by chandrams** [comment]
This issue is no longer seen.
